### ISSUE TITLE
MkDocs 0.17.x support

### ISSUE THREAD

**Issue by charlesreid1** [notpushkin/mkdocs-alabaster#16]
Running this theme with latest version of mkdocs shows the following error:

```
$ mkdocs serve
INFO    -  Building documentation...
WARNING -  The theme 'alabaster' does not appear to have a configuration file. Please upgrade to a current version of the theme.
INFO    -  Cleaning site directory
...
```

Versions of mkdocs and mkdocs-alabaster:

```
mkdocs==0.17.3
mkdocs-alabaster==0.7.4
```

**Comment by charlesreid1** [comment]
Theme documentation is also giving a 404 (I suggest moving it to Github Pages so you don't have to worry about it.)

If this theme/repo is retired, maybe update [the mkdocs wiki](https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes) so your theme isn't listed at the top. But hopefully you're still developing it!

**Comment by notpushkin** [comment]
Hey Chaz, thanks for reaching out!

I'm not actively using mkdocs anymore, so unfortunately won't be able to spend too much time on this. mkdocs 0.17 introduced some breaking changes, so if you could stick with 0.16.x for a while, this would be one workaround. Otherwise I guess I'll have some free time a bit later this week. Alternatively, would be nice if you could help out with a PR :)

**Comment by charlesreid1** [comment]
I have forked and am working on a PR now... :)

**Comment by Mach7Seven** [comment]
Hi, I'm using OSX 10.10. 

To suppress the error I've created a file inside alabaster's directory called **mkdocs_theme.yml** (here that path is **/Library/Python/2.7/site-packages/alabaster**) and wrote the following inside:

```
language: en 
static_templates: 
    - 404.html 
```


The error is gone. Check [https://www.mkdocs.org/user-guide/custom-themes/#theme-configuration](https://www.mkdocs.org/user-guide/custom-themes/#theme-configuration) for more info.
